### PR TITLE
Updated current database

### PR DESCRIPTION
**Pull request by salixh5**
Some Tofugu links didn't work anymore or didn't link directly to the
current page. Updated the links and the page titles.

Removed pages that don't exist anymore.

Fixed slight formatting errors and added new search words in some cases.

### CODE REVIEW

**Comment by salixh5** [comment]
I also wonder: Is it necessary to always include the romaji version to a certain entry's search words, even if the same word is already included in hiragana? Most of the current entries do this, but not all (for example entries with Id 13-15 don't).
But [a search for "to"](http://jisho.org/search/to) still correctly renders that exact entry. So I reckon these are not necessary?

**Comment by salixh5** [comment]
Added another commit that removes romaji which I think are probably superfluous.

**Comment by salixh5** [comment]
I think I've cleaned up the original database enough after this commit to start working on adding new entries or adding to existing entries. Will wait for your opinion on what I've done so far, though, before I begin with this task.

**Comment by Kimtaro** [comment]
Great cleanup! Thank you! 💯

There was just one issue, that I tried to amend to this PR, but my Git skills failed me. I had to put back in entry 44 on rendaku. Without it the IDs for the subsequent entries got shifted, which would cause the last entry to appear twice in the DB - once with its old ID and once with the new.

It's in this commit: https://github.com/Jisho-org/jisho-notes/commit/4f07967f4a5dc5068ea589bda7c151b866eb24e0

I emptied out its `Searchables` though, so it won't show up in searches. And you can have arbitrary "attributes" before the `Note:` part, so I retained the old searchables to make it easy to reinstate the entry if we find another good article on rendaku.

**Comment by Kimtaro** [comment]
Just updated the site to this version!

**Comment by salixh5** [comment]
Ok so the old database doesn't get replaced but overwritten? Do you think this behavior is good? Personally I'd think it's easy enough to reinstate old entries if needed by just looking into older commits. Undocumented arbitrary attributes also seem a little bit odd to me overall.

Of course if that's how it is, alright. I have no idea how the rest of the site works so maybe this is much better than changing anything else.

**Comment by Kimtaro** [comment]
The importer looks up entries by the Id - if it exists it is overwritten, if not it's created. All the importers in Jisho work this way. Deletions was something I decided to tackle "at some later date" :)

But it also means that Id's can be unique over time. It would be odd if the note for すみません was 46 in one version of the file and 45 in another.

**Comment by salixh5** [comment]
True, not having changing Ids for the same entry is of course something that can be very good. I thought of the file as basically being the database, but I guess it makes sense to think of it as a changeset, then.

**Comment by Kimtaro** [comment]
Yeah, it's the source database, but it's imported into the Jisho internal database, essentially just like all the other data sources that Jisho uses. It makes it easier for me if the internal database is just used for search, and not holding the original data.

**Comment by Kimtaro** [comment]
The idea behind it being that the internal database can be recreated by importing all the source data files from scratch.

**Pull request merged**
