### PR TITLE
Imabi Step 1

### PR DESCRIPTION
**Pull request by salixh5**
It took me some time, but I made a first step towards adding imabi.net links to the entries. Next step would be making new entries.

### CODE REVIEW

**Comment by salixh5** [comment]
By the way, 2 months ago when I was slacking at work I made this little tool: https://github.com/jeifour/jisho-notes/tree/manager/manager

It's a really simple website that can read and write these files basically. It doesn't know about stuff like "Searchables-old:" or that Ids are supposed to never change so one should still pay attention when using it and some manual editing of the resulting file is still needed, but it makes it a bit more convenient to look at and edit.

Feel free to give it a try.

**Comment by Kimtaro** [comment]
This is fantastic! Having these imabi links is a great addition 👍

I tried the manager and it works great. I was manually editing everything in the text file before, but this is much easier 😄 It's sorely needed now that the file is growing larger and is open for editing by anyone. But it also signals to me that maybe the HTML-inside-Markdown-format is a little more flexible than what is actually needed. However that's a problem for another day.

I'm adding a little spacing between the rendered `<li>`'s on Jisho so it's easier to see that there are different sites in a note.

I'll merge this now and try to push it out tomorrow with some other changes I have lined up.

As always, sorry for being super slow with responding `m(_ _)m`

**Comment by Kimtaro** [comment]
I forgot one thing. The one change I would make for these imabi links is to include the individual topics for the links that are a group of numbered links.

**Comment by salixh5** [comment]
Yeah I was thinking about that, and also why I only updated existing entries for now, to see what you think is the right way to go forward with this. Unfortunately while the content on imabi should be very helpful for learning Japanese (and sometimes much more in-depth than other sites), the structure of the website is a bit amateur-ish and in some ways lacks consistency.

If you don't have the spare time to make the adjustment, I'll change the link titles between christmas and new year.

**Comment by Kimtaro** [comment]
I'll be spending the next few days improving search performance and adding another server for redundancy, as there might be some traffic spikes coming up. So if you want to fix the link names that'd be great! But no rush, I don't see the current link names as an issue that has to be fixed quickly.

**Comment by Kimtaro** [comment]
I've deployed this to production \o/

By the way, how would you prefer to be attributed when I mention these changes on the forum? Github link, forum handle, or something else?

**Comment by salixh5** [comment]
Alright great. As for me, I don't need an attribution, but I think something like "thanks to Github contributors" would be good.

**Pull request merged**
